# Generated by Django 5.1.5 on 2025-01-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, unique=True)),
                ('customer_number', models.IntegerField()),
                ('customer_email', models.CharField(max_length=25)),
                ('customer_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.city')),
            ],
        ),
    ]
