# Generated by Django 5.1.5 on 2025-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_del',
            field=models.BooleanField(default=False),
        ),
    ]
