# Generated by Django 5.1.5 on 2025-01-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_customer_customer_del'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_del',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_number',
            new_name='number',
        ),
    ]
