# Generated by Django 5.1.5 on 2025-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_rename_delete_customer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
